### ISSUE TITLE
In the 0.17.0 package, the included linux-arm64 liblmdb.so is not arm64

### ISSUE THREAD

**Issue by hlindqvist** [CoreyKaylor/Lightning.NET#178]
After updating my project from using the 0.16.0 to the 0.17.0 nuget package, I started getting mysterious errors like this:

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'lmdb' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
/app/lmdb.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/lmdb.so: cannot open shared object file: No such file or directory
/app/liblmdb.so: wrong ELF class: ELFCLASS32
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/liblmdb.so: cannot open shared object file: No such file or directory
/app/lmdb: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/lmdb: cannot open shared object file: No such file or directory
/app/liblmdb: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.11/liblmdb: cannot open shared object file: No such file or directory

   at LightningDB.Native.Lmdb.mdb_env_create(IntPtr& env)
   at LightningDB.LightningEnvironment..ctor(String path, EnvironmentConfiguration configuration)
...
```

But the file liblmdb.so was indeed there, just as with my previous builds.

Looking closer I see:

```
liblmdb.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, with debug_info, not stripped
```

There seems to have been some mixup in 84385acb853831cdc8b378469fe34f78617da42d such that the same file ended up under multiple architectures:

```
$ sha256sum Lightning.NET/src/LightningDB/runtimes/linux-arm*/native/liblmdb.so
a542c901e05c088bf3429840fa0972abe354ffca95bf97f67c4ab7e677e1c9ac  linux-arm/native/liblmdb.so
a542c901e05c088bf3429840fa0972abe354ffca95bf97f67c4ab7e677e1c9ac  linux-arm64/native/liblmdb.so
$
```

**Comment by CoreyKaylor** [comment]
Thanks for reporting. This is the file that produces the native binaries and copies into the respective nuget folder path.

https://github.com/CoreyKaylor/Lightning.NET/blob/master/lmdb/compile-lmdb-macos.sh

I've been blind many times before, but I'm struggling to see where it's copied the same file into different folders. I'm likely going to need to add something to validate at the end of the script that all the files are different.

Initially my thought was that it was maybe the switch to podman, but I read initially and re-read and it does appear to support the --platform switch the same as the docker cli, so I'm doubtful that's it either.

**Comment by CoreyKaylor** [comment]
I just tested the script and it produces what I would expect even after verifying with the file command with an exception for the 32 bit ARM version. My podman setup needs some changes to compile the 32 bit with QEMU that I need to look into. I'm not saying this is what caused it, it's quite possible I just accidentally did something wonky here.

Separately just for some sanity, I'm drying up the script and adding a step to verify that for all supported targets there is a distinct hash for each file. Hopefully that will help prevent this kind of thing in the future but unfortunately with supporting so many targets it can be easy to miss details.

**Comment by hlindqvist** [comment]
> Thanks for reporting. This is the file that produces the native binaries and copies into the respective nuget folder path.
> 
> https://github.com/CoreyKaylor/Lightning.NET/blob/master/lmdb/compile-lmdb-macos.sh
> 
> I've been blind many times before, but I'm struggling to see where it's copied the same file into different folders. I'm likely going to need to add something to validate at the end of the script that all the files are different.
> 
> Initially my thought was that it was maybe the switch to podman, but I read initially and re-read and it does appear to support the --platform switch the same as the docker cli, so I'm doubtful that's it either.

Yeah, I can't spot any reason why that script would produce the incorrect result as the corresponding `--platform` is specified in each step. (Unless of course there was a previous version which didn't have that?)

One thing I did note regarding `--platform` is this interesting "sticky" behavior:
"Unless overridden, subsequent lookups of the same image in the local storage matches this platform, regardless of the host."
https://docs.podman.io/en/stable/markdown/podman-run.1.html#platform-os-arch


> I just tested the script and it produces what I would expect even after verifying with the file command with an exception for the 32 bit ARM version. My podman setup needs some changes to compile the 32 bit with QEMU that I need to look into. I'm not saying this is what caused it, it's quite possible I just accidentally did something wonky here.
> 
> Separately just for some sanity, I'm drying up the script and adding a step to verify that for all supported targets there is a distinct hash for each file. Hopefully that will help prevent this kind of thing in the future but unfortunately with supporting so many targets it can be easy to miss details.

Ok, sounds good. That ought to catch the problem if it somehow continues happening.

**Comment by CoreyKaylor** [comment]
Pushed the first attempt at DRYing up the build script for the native binaries 18ab906bba792e98f. It took a while for me to get back to a state that everything would compile. The switch to podman did cause some issues that weren't apparent initially. I've now updated to using docker-cli with colima. This was much closer to the original behavior of the docker desktop and multi-platform builds.

I still need to add the piece to validate everything supported has distinct output, but I'll try and tackle that tomorrow if I have time.

**Comment by CoreyKaylor** [comment]
I've added newly compiled binaries using the updated script in 0d6f01d7dc0d99eebfd85328f4855bf1a73f91ca.

Here is the output from the linux/arm64 version.
`linux-arm64/native/liblmdb.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped`

**Comment by CoreyKaylor** [comment]
Nuget package 0.17.1 has been published with these changes as well. Let me know if it helps.

**Comment by hlindqvist** [comment]
> Nuget package 0.17.1 has been published with these changes as well. Let me know if it helps.

That indeed seems to fix the problem. Thank you!
